### ISSUE TITLE
does this formula assume docker is installed?

### ISSUE THREAD

**Issue by BadgerOps** [salt-formulas/salt-formula-prometheus#4]
Hello,

Thanks for the prometheus formula! I've been trying to use it in a vagrant environment in preparation for rolling it out to our production environment. I had a bit of an issue getting it to apply initially until I started looking at the SLS files. 

I noticed [here](https://github.com/salt-formulas/salt-formula-prometheus/blob/master/prometheus/server.sls#L4) that in order to apply the server role a 'docker' reference must be defined in pillar. Does this mean this formula is designed specifically for a docker environment, and if so should the documentation be updated to reflect this?

I'd be happy to do so, but it would be nice to have docker be optional instead of assumed. (Again, I'm absolutely  willing to write the code to do so)

Thanks!

**Comment by asyncmind0** [comment]
not sure why this is the official salt-formula for prometheus under salt-formulas

https://github.com/richerve/prometheus-formula is much cleaner and does not require docker and k8

also prometheus official doco points to another formula which is again written in a non-standard weird way.

**Comment by BadgerOps** [comment]
Thanks for the link @jagguli - I'll check that formula out.

**Comment by fpytloun** [comment]
Hello,

this formula was initially designed to be used with Docker (salt-formula-docker). There's PR #2 to implement local docker-less setup.
Also note that salt-formulas doesn't belong under Saltstack or being anything like Saltstack official.

Anyway any contribution (including documentation, etc.) is appreciated.

**Comment by BadgerOps** [comment]
Thanks for the update @fpytloun !
